
library("lme4")
library("lmerTest")
library("dplyr")
library("nlme")
library("lsmeans")
library("PMCMRplus")
library("car")
library("multcomp")
library("dunn.test")
library("MASS")
############################Worker sample
dataRCP1<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/WorkerSample/RCP1.csv")
attach(dataRCP1)
shapiro.test(Quantity_Mean)
levels_order <- c("L_Head", "P_AT", "10Nur_AT","10For_AT","23Nur_AT","23For_AT")
dataRCP1$Tissue <- factor(dataRCP1$Tissue, levels=levels_order)
dataRCP1$Colony <- factor(dataRCP1$Colony)
boxplot(Quantity_Mean~Tissue,data = dataRCP1)
kruskal.test(Quantity_Mean~Tissue, data = dataRCP1)
result <- dunn.test(dataRCP1$Quantity_Mean, dataRCP1$Tissue, method="bonferroni")
boxplot(Quantity_Mean~Colony,data = dataRCP1)
kruskal.test(Quantity_Mean~Colony, data = dataRCP1)
result <- dunn.test(dataRCP1$Quantity_Mean, dataRCP1$Colony, method="bonferroni")


dataGapDH_ppil2_RPL13A<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/WorkerSample/GapDH_ppil2_RPL13A.csv")
attach(dataGapDH_ppil2_RPL13A)
shapiro.test(GeoMean)
levels_order <- c("L_Head", "P_AT", "10Nur_AT","10For_AT","23Nur_AT","23For_AT")
dataGapDH_ppil2_RPL13A$Tissue <- factor(dataGapDH_ppil2_RPL13A$Tissue, levels=levels_order)
dataGapDH_ppil2_RPL13A$Colony <- factor(dataGapDH_ppil2_RPL13A$Colony)
boxplot(GeoMean~Tissue,data = dataGapDH_ppil2_RPL13A)
model1.1 <- lme(GeoMean~Tissue, random = ~1|Colony, data=dataGapDH_ppil2_RPL13A)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))
boxplot(GeoMean~Colony,data = dataGapDH_ppil2_RPL13A)
kruskal.test(GeoMean~Colony, data = dataGapDH_ppil2_RPL13A)
mean(GeoMean)
sd(GeoMean)
cv<-sd(GeoMean)/mean(GeoMean)
sum(cv)




dataOrco<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/WorkerSample/Orco.csv")
attach(dataOrco)
shapiro.test(NorValue)
levels_order <- c("L_Head", "P_AT", "10Nur_AT","10For_AT","23Nur_AT","23For_AT")
dataOrco$Tissue <- factor(dataOrco$Tissue, levels=levels_order)
dataOrco$Colony <- factor(dataOrco$Colony)
boxplot(NorValue~Tissue,data = dataOrco)
model1.1 <- lme(NorValue~Tissue, random = ~1|Colony, data=dataOrco)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))





dataIR25a<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/WorkerSample/IR25a.csv")
attach(dataIR25a)
shapiro.test(sqrt(NorValue))
levels_order <- c("L_Head", "P_AT", "10Nur_AT","10For_AT","23Nur_AT","23For_AT")
dataIR25a$Tissue <- factor(dataIR25a$Tissue, levels=levels_order)
dataIR25a$Colony <- factor(dataIR25a$Colony)
boxplot(NorValue~Tissue,data = dataIR25a)
model1.1 <- lme(sqrt(NorValue)~Tissue, random = ~1|Colony, data=dataIR25a)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))

########################Queen Samples
dataRCP1<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/QueenSample/cDNA_Amy/RCP1.csv")
attach(dataRCP1)
shapiro.test(Quantity_Mean)
bartlett.test(Quantity_Mean~Tissue,data = dataRCP1)
kruskal.test(Quantity_Mean~Tissue, data = dataRCP1)
result <- dunn.test(dataRCP1$Quantity_Mean, dataRCP1$Tissue, method="bonferroni")
levels_order <- c("L_Head", "P_AT", "A_AT")
dataRCP1$Tissue <- factor(dataRCP1$Tissue, levels=levels_order)
boxplot(Quantity_Mean~Tissue,data = dataRCP1)
kruskal.test(Quantity_Mean~Tissue, data = dataRCP1)
result <- dunn.test(dataRCP1$Quantity_Mean, dataRCP1$Tissue, method="bonferroni")
bartlett.test(Quantity_Mean~Colony,data = dataRCP1)
boxplot(Quantity_Mean~Colony,data = dataRCP1)
aov.modelColony<-aov(Quantity_Mean~Colony,data = dataRCP1)
summary(aov.modelColony)


dataAct2_GapDH_ppil2<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/QueenSample/cDNA_Amy/Act2_GapDH_ppil2.csv")
attach(dataAct2_GapDH_ppil2)
shapiro.test(log(GeoMean))
dataAct2_GapDH_ppil2$Colony <- factor(dataAct2_GapDH_ppil2$Colony)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataAct2_GapDH_ppil2$Batch <- factor(dataAct2_GapDH_ppil2$Batch)
dataAct2_GapDH_ppil2$Tissue <- factor(dataAct2_GapDH_ppil2$Tissue, levels=levels_order)
boxplot(GeoMean~Tissue,data = dataAct2_GapDH_ppil2)
model1.1 <- lme(log(GeoMean)~Tissue, random = ~1|Colony/Batch, data=dataAct2_GapDH_ppil2)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))
boxplot(GeoMean~Colony, dataAct2_GapDH_ppil2)
model1.2 <- lme(log(GeoMean)~Colony, random = ~1|Batch, data=dataAct2_GapDH_ppil2)
anova(model1.2)
mean(GeoMean)
sd(GeoMean)
cv<-sd(GeoMean)/mean(GeoMean)
sum(cv)


dataOrco<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/QueenSample/cDNA_Amy/Orco.csv")
attach(dataOrco)
shapiro.test(sqrt(NorValue))
dataOrco$Colony <- factor(dataOrco$Colony)
dataOrco$Batch<-factor(dataOrco$Batch)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataOrco$Tissue <- factor(dataOrco$Tissue, levels=levels_order)
boxplot(NorValue~Tissue,data = dataOrco)
model1.1 <- lme(sqrt(NorValue)~Tissue, random = ~1|Colony/Batch, dataOrco)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))


dataIR25A<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/QueenSample/cDNA_Amy/IR25A.csv")
attach(dataIR25A)
shapiro.test(log(NorValue))
dataIR25A$Colony <- factor(dataIR25A$Colony)
dataIR25A$Batch<-factor(dataIR25A$Batch)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataIR25A$Tissue <- factor(dataIR25A$Tissue, levels=levels_order)
boxplot(NorValue~Tissue,data = dataIR25A)
model1.1 <- lme(log(NorValue)~Tissue, random = ~1|Colony/Batch, dataIR25A)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))


#########################Drone Samples
dataRCP1<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/DroneSample/RCP1.csv")
attach(dataRCP1)
shapiro.test(Quantity_Mean)
bartlett.test(Quantity_Mean~Tissue,data = dataRCP1)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataRCP1$Tissue <- factor(dataRCP1$Tissue, levels=levels_order)
boxplot(Quantity_Mean~Tissue,data = dataRCP1)
aov.modelTissue<-aov(Quantity_Mean~Tissue,data = dataRCP1)
summary(aov.modelTissue)
model1.1 <- lme(Quantity_Mean~Tissue, random = ~1|Batch, data = dataRCP1)
anova(model1.1)
boxplot(Quantity_Mean~Colony,data = dataRCP1)
aov.modelColony<-aov(Quantity_Mean~Colony,data = dataRCP1)
summary(aov.modelColony)
model1.2 <- lme(Quantity_Mean~Colony, random = ~1|Batch, data = dataRCP1)
anova(model1.2)

dataGAPDH_Rab1A_RPL13A<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/DroneSample/GAPDH_Rab1A_RPL13A.csv")
attach(dataGAPDH_Rab1A_RPL13A)
shapiro.test(log(GeoMean))
levels_order <- c("L_Head", "P_AT", "A_AT")
dataGAPDH_Rab1A_RPL13A$Colony <- factor(dataGAPDH_Rab1A_RPL13A$Colony)
dataGAPDH_Rab1A_RPL13A$Batch <- factor(dataGAPDH_Rab1A_RPL13A$Batch)
dataGAPDH_Rab1A_RPL13A$Tissue <- factor(dataGAPDH_Rab1A_RPL13A$Tissue, levels=levels_order)
boxplot(GeoMean~Tissue,data = dataGAPDH_Rab1A_RPL13A)
model1.1 <- lme(log(GeoMean)~Tissue, random = ~1|Batch/Colony, data=dataGAPDH_Rab1A_RPL13A)
anova(model1.1)
model1.2 <- lme(log(GeoMean)~Colony, random = ~1|Batch, data=dataGAPDH_Rab1A_RPL13A)
anova(model1.2)
boxplot(GeoMean~Colony, dataGAPDH_Rab1A_RPL13A)

dataOrco<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/DroneSample/Orco.csv")
attach(dataOrco)
shapiro.test(sqrt(Normalized_data))
dataOrco$Colony <- factor(dataOrco$Colony)
dataOrco$Batch <- factor(dataOrco$Batch)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataOrco$Tissue <- factor(dataOrco$Tissue, levels=levels_order)
boxplot(Normalized_data~Tissue,data = dataOrco)
model1.1 <- lme(sqrt(Normalized_data)~Tissue, random = ~1|Batch/Colony, data=dataOrco)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))
anova(model1.1)

dataIR25A<- read.csv("D:/Postdoct/2023.06.26 OR11 expression/QPCR/R_analysis/DroneSample/IR25A.csv")
attach(dataIR25A)
shapiro.test(log(Normalized_data))
dataIR25A$Colony <- factor(dataIR25A$Colony)
dataIR25A$Batch <- factor(dataIR25A$Batch)
levels_order <- c("L_Head", "P_AT", "A_AT")
dataIR25A$Tissue <- factor(dataIR25A$Tissue, levels=levels_order)
boxplot(Normalized_data~Tissue,data = dataIR25A)
model1.1 <- lme(log(Normalized_data)~Tissue, random = ~1|Batch/Colony, data=dataIR25A)
residuals_model <- residuals(model1.1)
fitted_values <- fitted(model1.1)
plot(fitted_values, residuals_model, main="Residuals vs Fitted", xlab="Fitted values", ylab="Residuals")
abline(h=0, col="red")
qqnorm(residuals_model)
qqline(residuals_model)
anova(model1.1)
summary(glht(model1.1, linfct = mcp(Tissue = "Tukey")))